import typing
import numpy as np
import random
import math
from collections import namedtuple


from .dataset import Dataset
from .ops import Op


class Batch:
    '''
    A (mini)batch generated by the batch generator.
    '''

    def __init__(self):
        '''
        Ctor.
        '''

        self.data = None
        self.label = None
        self.idx = None

class BatchGenerator:
    '''
    Batch generator.
    Returned batches have the following properties:
      data: numpy array holding batch data of shape (s, SHAPE_OF_DATASET_SAMPLES).
      label: numpy array holding batch labels of shape (s, SHAPE_OF_DATASET_LABELS).
      idx: numpy array with shape (s,) encoding the indices of each sample in the original dataset.
    '''

    def __init__(self, dataset: Dataset, num: int, shuffle: bool, op: Op=None):
        '''
        Ctor.
        Dataset is the dataset to iterate over.
        num is the number of samples per batch. the number in the last batch might be smaller than that.
        shuffle controls whether the sample order should be preserved or not.
        op is an operation to apply to input samples.
        Raises TypeError on invalid argument types.
        Raises ValueError on invalid argument values, such as if num is > len(dataset).
        '''

        self.batch_array = []
        self.n_batches = math.ceil(len(dataset) / num)
        for n_batch in range(self.n_batches):
            try:
                d = []
                l = []
                idx = []

                for i in range(num):
                    sample = dataset[n_batch*num + i]
                    if op:
                        s = namedtuple('Sample', ['idx', 'data', 'label'])
                        sample = s(sample.idx,op(sample.data),sample.label)
                        #sample.data = op(sample.data)  # is sample immutable ?
                    d.append(sample.data)
                    l.append(np.int64(sample.label))
                    idx.append(sample.idx)
            except IndexError:
                d = []
                l = []
                idx = []

                for i in range(len(dataset) % num):
                    sample = dataset[n_batch*num + i]
                    if op:
                        s = namedtuple('Sample', ['idx', 'data', 'label'])
                        sample = s(sample.idx,op(sample.data),sample.label)
                    d.append(sample.data)
                    l.append(np.int64(sample.label))
                    idx.append(sample.idx)

            batch = Batch()
            batch.data = np.array(d)
            batch.label = np.array(l)
            batch.idx = np.array([idx])
            self.batch_array.append(batch)
            if shuffle:
                random.shuffle(self.batch_array)



    def __len__(self) -> int:
        '''
        Returns the total number of batches the dataset is split into.
            This is identical to the total number of batches yielded every time the __iter__ method is called.
        '''

        return self.n_batches

    def __iter__(self) -> typing.Iterable[Batch]:
        '''
        Iterate over the wrapped dataset, returning the data as batches.
        '''

        # The "yield" keyword makes this easier

        for i in range(self.__len__()):
            yield self.batch_array[i]


